### ISSUE TITLE
PostalCode issue

### ISSUE THREAD

**Issue by rlee1990** [aloisdeniel/flutter_geocoder#2]
Receiving null for postal code on Android devices. Works fine on IOS devices. The postal code shows in the address line but not when calling it on its own in Android.

**Comment by aloisdeniel** [comment]
Hi, on which device did you try it ?

**Comment by rlee1990** [comment]
@aloisdeniel i tried on a note 8 note 4 nexus 5x

**Comment by fazil-augr** [comment]
I am also facing this problem. I tried different devices and emulator in android. Why it is not showing pincode . How to solve the issue?

**Comment by aloisdeniel** [comment]
It should be fixed now with 0.1.2.

**Comment by fazil-augr** [comment]
ya it's working after updating. Thanks a lot.

**Comment by aloisdeniel** [comment]
Great!
