### ISSUE TITLE
flutter 1.7.8+hotfix.3 on stable channel | geocoder: 0.1.2

### ISSUE THREAD

**Issue by ghost** [aloisdeniel/flutter_geocoder#24]
I have updated **flutter 1.7.8+hotfix.3** on **stable channel**

Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #2
E/AndroidRuntime(10984): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime(10984): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
E/AndroidRuntime(10984): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
E/AndroidRuntime(10984): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(10984): 	at com.aloisdeniel.geocoder.GeocoderPlugin$1.doInBackground(GeocoderPlugin.java:79)
E/AndroidRuntime(10984): 	at com.aloisdeniel.geocoder.GeocoderPlugin$1.doInBackground(GeocoderPlugin.java:72)
E/AndroidRuntime(10984): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(10984): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10984): 	... 4 more

How to fix this issue

Thanks

**Comment by andriiIliunin** [comment]
+ 1, the same crash (in example too)

**Comment by rrnicolay** [comment]
I'm facing this isso too. It worked on v1.5.4.

**Comment by Eimji** [comment]
a PR is waiting for being merged here https://github.com/aloisdeniel/flutter_geocoder/pull/15

**Comment by bayuly94** [comment]
same crash

**Comment by rrnicolay** [comment]
Found this commit in another thread. Solved for me.
Put this on pubspec.yaml:
```
geocoder:
    git:
      url: https://github.com/Eimji/flutter_geocoder.git
      ref: bc34cfe473bfd1934fe098bb7053248b75200241
```

**Comment by ghost** [comment]
@rrnicolay Thanks, It is working fine
