### ISSUE TITLE
Local Information

### ISSUE THREAD

**Issue by coding-era** [aloisdeniel/flutter_geocoder#27]
Hi,

Where does the local geolocations come from? Like is it built in the android device? Because the only way to get the geocodes as far as I know is to get it from google maps and other services. How does this plugin locally retrieve the geocode of different addresses?

**Comment by aloisdeniel** [comment]
The Android system provides [standardised API to get such informations](https://developer.android.com/reference/android/location/Geocoder). Each device constructor can choose a specific service to get data (most of them are using Google services, but it is a different story in China for example).
