### ISSUE TITLE
Exception in Geocoder.google

### ISSUE THREAD

**Issue by vjrj** [aloisdeniel/flutter_geocoder#3]
Trying to use  Geocoder.google` I get this exception on Android:

> E/flutter ( 4124): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
> E/flutter ( 4124): type 'List<dynamic>' is not a subtype of type 'List<Map<dynamic, dynamic>>'
> E/flutter ( 4124): #0      GoogleGeocoding._send (package:geocoder/services/distant_google.dart:42:29)
> E/flutter ( 4124): <asynchronous suspension>
> E/flutter ( 4124): #1      GoogleGeocoding.findAddressesFromCoordinates

**Comment by aloisdeniel** [comment]
Should be fixed in latest version.
