### ISSUE TITLE
Geocoder.google not working

### ISSUE THREAD

**Issue by gabxap** [aloisdeniel/flutter_geocoder#34]
Hi, I have enable the Geocoding api on Google Cloud Platform in order to use it over Geocoder.Google. It looks everything working on the Google side but when i try to bring the data it shows error and doesn't return anything.

`    final coordinates = new Coordinates(-12.0785151, -77.0557978);

    var addresses =
        await Geocoder.google(apikey)
            .findAddressesFromCoordinates(coordinates);
    var ad = addresses.first;
    print(ad.toMap());`

I got this on my terminal

Performing hot restart...                                               
Restarted application in 1,037ms.
flutter: distrito
[VERBOSE-2:ui_dart_state.cc(144)] Unhandled Exception: Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:220:5)
#1      _MyHomePageState.getDistrict (package:google_maps/main.dart:38:24)
<asynchronous suspension>
#2      _MyHomePageState.initState (package:google_maps/main.dart:54:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4085:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#11     Ele<…>
        [C3.1 BF945B7C-A3F8-43B8-9922-CE812241D441 192.168.1.16:53918<->172.217.8.78:443]
        Connected Path: satisfied (Path is satisfied), interface: en0
        Duration: 68.995s, DNS @0.000s took 1.039s, TCP @1.041s took 0.072s, TLS took 0.179s
        bytes in/out: 4659/1725, packets in/out: 14/12, rtt: 0.074s, retransmitted packets: 0, out-of-order packets: 0
        [C4.1 C628BB9C-C2AF-4FFB-ADDB-57DCE7EE6F35 192.168.1.16:54192<->172.217.8.138:443]
        Connected Path: satisfied (Path is satisfied), interface: en0
        Duration: 0.404s, DNS @0.000s took 0.019s, TCP @0.021s took 0.081s, TLS took 0.196s
        bytes in/out: 4844/1475, packets in/out: 10/9, rtt: 0.078s, retransmitted packets: 0, out-of-order packets: 0

![image](https://user-images.githubusercontent.com/24376974/69903558-fb306200-1368-11ea-95cf-dcb519612247.png)

**Comment by JunjaK** [comment]
If you're GCP's geocoding is working well, then how about use this code?

```
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

_getGoogleAddress(address) async{
    const _host = 'https://maps.google.com/maps/api/geocode/json';
    const apiKey = key.key;
    var encoded = Uri.encodeComponent(address);
    final uri = Uri.parse('$_host?key=$apiKey&address=$encoded');

    http.Response response = await http.get (uri);
    final responseJson = json.decode(response.body);
    print(responseJson['results'][0]['geometry']['location']);
}
```

if you put address in this function, the function print out  latitude and longitude

**Comment by JunjaK** [comment]
Sorry, I wrote address version, coordiates version is this
```
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

_getGooglecoo() async{
    const _host = 'https://maps.google.com/maps/api/geocode/json';
    const apiKey = key.key;
    var latitude = '35.183071';
    var longitude = '136.902576';

    final uri = Uri.parse('$_host?key=$apiKey&latlng=$latitude,$longitude');
    print(uri);
    http.Response response = await http.get (uri);
    final responseJson = json.decode(response.body);
    print(responseJson);
  }
```
Just put latitude and longitude in your ones

**Comment by congfandi** [comment]
i git this issue guyss.. please help

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by pacakman** [comment]
Hello, I have the same problem here. Do you find the solution?

**Comment by ali-tafakkori** [comment]
+1

**Comment by ali-tafakkori** [comment]
I find problem. I test by Postman.

Request:
`https://maps.google.com/maps/api/geocode/json?key=AIzaSyCmt#################&latlng=46.05,37.95&language=fa`

Response:
```
{
    "error_message": "You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started",
    "results": [],
    "status": "REQUEST_DENIED"
}
```
According to the response, needs to enable Billing on the Google Cloud.

**Comment by gabxap** [comment]
> I find problem. I test by Postman.
> 
> Request:
> `https://maps.google.com/maps/api/geocode/json?key=AIzaSyCmt#################&latlng=46.05,37.95&language=fa`
> 
> Response:
> ```
> {
>     "error_message": "You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started",
>     "results": [],
>     "status": "REQUEST_DENIED"
> }
> ```
> According to the response, needs to enable Billing on the Google Cloud.
> 

I already deleted the project for this but I think this may be a solution since I didn't remember enabling billing for this functionality.
