### ISSUE TITLE
Real API keys commited

### ISSUE THREAD

**Issue by vjrj** [aloisdeniel/flutter_geocoder#4]
If you are not aware, I see a real GoogleMap API key in:
https://github.com/aloisdeniel/flutter_geocoder/blob/fffeb243f6b3e1b3c5c35bcce4874a1fba3e0f66/example/lib/main.dart#L184

To prevent misuse by others I recommend you to invalidate it or clean with `bfg`, and just commit a sample key like "YOUR_GOOGLE_API_KEY_HERE".

More info:
https://blog.github.com/2013-01-25-secrets-in-the-code/

**Comment by aloisdeniel** [comment]
Thanks, didn't notice that! :)
