### ISSUE TITLE
Error: Getter not found

### ISSUE THREAD

**Issue by morad00** [aloisdeniel/flutter_geocoder#5]
I tried to use `gecoder` but it failed in debugging 

![screen shot 2018-08-07 at 11 49 09 am](https://user-images.githubusercontent.com/37535179/43768942-d2ebaa52-9a38-11e8-99c3-45570f008a3b.png)

**Comment by neerajyadv** [comment]
I am also having same the issue. Alois just need to change UT8 and JSON to utf8 and json as Dart 2 is now official. Hope he does it soon.

**Comment by aloisdeniel** [comment]
Should be fixed with latest version.

**Comment by neerajyadv** [comment]
Yeah, it's now working fine. Thank You.
