### ISSUE TITLE
Not working on newer devices

### ISSUE THREAD

**Issue by aTeamSolace** [aloisdeniel/flutter_geocoder#50]
Hello, I'm using **geocoder: ^0.2.1** this plugin. This is working fine on lower version devices but not working on the above version 9.0 devices. Please let me know the solution.

**Comment by aTeamSolace** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [Version 10.0.18362.1139], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.50.1)
[√] Connected device (4 available)

• No issues found!

**Comment by aTeamSolace** [comment]
android {
    compileSdkVersion 30

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.shubham.adam_company_consumer_app"
        minSdkVersion 16
        targetSdkVersion 30
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

**Comment by aTeamSolace** [comment]
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

**Comment by aTeamSolace** [comment]
```
getCurrentLocation() async {
   Position position = await Geolocator.getCurrentPosition(
       desiredAccuracy: LocationAccuracy.high);
   final coordinates = new Coordinates(position.latitude, position.longitude);
   var addresses =
       await Geocoder.local.findAddressesFromCoordinates(coordinates);
   var first = addresses.first;
   if (this.mounted) {
     setState(() {
       latLng = new LatLng(position.latitude, position.longitude);
       currentAddress = first.featureName +
           " " +
           first.subLocality +
           " " +
           first.subAdminArea;
       countryName = first.countryName.toLowerCase();
       getServices();
     });
   }
 }
```

**Comment by ashvininfikey** [comment]
Please let me know if you found any solution for this issue.

Thanks.

**Comment by diegopq** [comment]
@aloisdeniel Apparently they no longer maintain the package since 2019 :(

**Comment by aTeamSolace** [comment]
> Please let me know if you found any solution for this issue.
> 
> Thanks.

I used [geolocator ](https://pub.dev/packages/geolocator)instead of geocoder
