### ISSUE TITLE
Calling function findAddressesFromCoordinates() throws MissingPluginException

### ISSUE THREAD

**Issue by vijaykanta** [aloisdeniel/flutter_geocoder#8]
I came across this plugin to satisfy my need of getting a formatted address for my geo coordinates. Included package in my YAML file and wrote the sample code sending sample but authentic coordinates and I was given the following error when calling the function `findAddressesFromCoordinates()`

`MissingPluginException(No implementation found for method findAddressesFromCoordinates on channel github.com/aloisdeniel/geocoder)`
`#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 9718): <asynchronous suspension>`
`E/flutter ( 9718): #1      LocalGeocoding.findAddressesFromCoordinates (package:geocoder/services/local.dart:13:41)
E/flutter ( 9718): <asynchronous suspension>`

I stopped debugging, and fresh started, but to no avail. Help!

**Comment by ROTGP** [comment]
I experienced this also. The error is misleading. It seems that adding more info (province, country, etc) to the address fixes the problem. Internally I think null results need to be handles better.

**Comment by hussainwali74** [comment]
The workaround for now is to reload the app.
facing the same issue, how do we solve this?

**Comment by aloisdeniel** [comment]
Hum ... strange behaviour. I have to check if the plugin system has evolved since I initiated the project structure. 

If not I will have to profile the app a lot more!

**Comment by iamjitendrasinh** [comment]
facing same issue any updates on it??

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method findAddressesFromCoordinates on channel github.com/aloisdeniel/geocoder)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      LocalGeocoding.findAddressesFromCoordinates (package:geocoder/services/local.dart:13:41)
<asynchronous suspension>
#2      _MyAppState.initPlatformState (package:location_example/main.dart:55:50)
<asynchronous suspension>
#3      _MyAppState.initState (package:location_example/main.dart:35:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
#8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
#9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
#10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
#12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
#14     runApp (package:flutter/src/widgets/binding.dart:780:7)
#15     main (package:location_example/main.dart:9:3)
#16     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
#21     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
#22     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by iamjitendrasinh** [comment]
Reloading whole app fix the issue may be Hot Reload cause the problem. anyway thanks for great library.

**Comment by stevenosse** [comment]
Just stop completely the app and then launch it again, that's actually what worked for me

**Comment by Vickycp** [comment]
stop debugging, restart the app  and then it  work fine without error

**Comment by NavdeepSinghBhati2562** [comment]
Restarting app works

**Comment by Sauvikn98** [comment]
Overflow on channel: github.com/aloisdeniel/geocoder.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.

I am getting this error after implementing geocoder. Seems like some internal issue in the package

**Comment by Vickycp** [comment]
> Overflow on channel: github.com/aloisdeniel/geocoder.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
> 
> I am getting this error after implementing geocoder. Seems like some internal issue in the package

Nope you need to restart your device then it's work properly

**Comment by Akshay-akkay** [comment]
Nope Restarting don't work.
Atleast on my configurations/IOS.

**Comment by SirMichaelJacob** [comment]
I'm having same issue with Geocoder. Reloading is not working. Please has anyone solved it?

**Comment by kocmeric** [comment]
Facing the same issue rn. Any updates??

**Comment by Ritsz123** [comment]
Facing this issue for live users, please mention a solution

**Comment by saharsheikhIntra** [comment]
facing the same issue stated above restart is not working as getting exception says
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_geocoder'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
