### ISSUE TITLE
findAddressesFromCoordinates Android Vs IOS

### ISSUE THREAD

**Issue by naumanahmed19** [aloisdeniel/flutter_geocoder#9]
why results are different on IOS and Android for findAddressesFromCoordinates?

**Comment by aloisdeniel** [comment]
Hello ! Yes, if you use `Geocoder.local` it uses the native geocoders from Apple and Google underneath. That's why you get different results.

If you want to have the same result you can still use the `Geocoder.google(<GOOGLE MAPS APIKEY>)` online geocoder (but it **needs an internet connection**).
